name: CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
        - name: Check out code into Go module directory
          uses: actions/checkout@v4

        - name: Setup Go 1.x
          uses: actions/setup-go@v4
          with:
            go-version: 1.22
        
        - name: Cache modules
          uses: actions/cache@v4
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: Get dependencies
          run: go mod tidy            

        - name: Tests
          run: go test -v ./...